### ISSUE TITLE
Compress-Archive removes the .git directories

### ISSUE THREAD

**Issue by nixonba** [Pacman1988/BackupAzureDevopsRepos#1]
Great script - love it. When testing I noticed the .git directories did not make it into the .zip. It seems there is [a problem with Compress-Archive](https://stackoverflow.com/questions/53551418/how-to-zip-archive-hidden-files-using-compress-archive) so an alternate compression method might be in order, or none at all.
Thanks,
Brian

**Comment by Pacman1988** [comment]
Hi Brian

You're right! I want to avoid third-party modules as good as I can. So I try a workaround. I make a list of the hidden files, unhide them, compress them, and hide them again.

You can try this branch: https://github.com/Pacman1988/BackupAzureDevopsRepos/blob/1-compress-archive-removes-the-git-directories/backup-azure-devops-repository.ps1

The only downside is the on the restore the hidden files are not hidden anymore. Else I see only the way with 7z, but I want to avoid third-party.

Can you try it out?

Marco

**Comment by Pacman1988** [comment]
No answer.
