### ISSUE TITLE
Pipe verbose into a separate log file

### ISSUE THREAD

**Issue by adagejchin** [Pacman1988/BackupAzureDevopsRepos#3]
I'm currently running the PS script through a task scheduler, and it's working great, but I don't have any other verbose visibility other than what Task Scheduler is telling me.  Is there a way to pipe the backup script's verbose to a separate log file?

**Comment by robvh1** [comment]
Think if you add Start-Transcript to the script it will also include the verbose output
fe.
Start-Transcript test.log
$VerbosePreference='Continue'
Write-Verbose 'test'
Stop-Transcript

type .\test.log
**********************
<...Personal Info Removed...>
**********************
Transcript started, output file is test.log
PS C:\> $VerbosePreference='Continue'
PS C:\> Write-Verbose 'test'
VERBOSE: test
PS C:\> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20240605113338
**********************
